apiVersion: v1
kind: Service
metadata:
  name: nexclipper-api
  labels:
    app: nexclipper-api
    version: v0.1
  namespace: nexclipper
spec:
  type: NodePort
  ports:
    - port: 10130
      protocol: TCP
      targetPort: 9000
      nodePort: 30100
      name: http
  selector:
    app: nexclipper-api