apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricark-api
  labels:
    app: metricark-api
    version: v1
  namespace: nex-system
spec:
  selector:
    matchLabels:
      app: metricark-api
  template:
    metadata:
      name: metricark-api
      labels:
        app: metricark-api
    spec:
      containers:
        - name: metricark-api
          image: nexclipper/monitorapi:main
          # resources:
          #   limits:
          #     memory: 1Gi
          #   requests:
          #     memory: 512Mi
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
              name: metricark-api
          env:
            - name: PROMETHEUS_ENDPOINT
              value: "http://nc-promscale-connector.nexclipper:9201"
            - name: REDIS_ENDPOINT
              value: "metricops"
            - name: REDIS_PORT
              value: '6379'