apiVersion: v1
kind: Service
metadata:
  name: metricark-api
  labels:
    app: metricark-api
  namespace: nex-system
spec:
  type: ClusterIP
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
      name: http
  selector:
    app: metricark-api