apiVersion: v1
kind: Service
metadata:
  name: metricark
  labels:
    app: metricark
  namespace: nex-system
spec:
  type: ClusterIP
  ports:
    - port: 8282
      protocol: TCP
      targetPort: 80
      name: http
  selector:
    app: metricark